### ISSUE TITLE
Add that the currentplayer only can update her result

### ISSUE THREAD

**Issue by birrejan** [JanGimenezLayola/ping-pong-manager#1]

**Comment by Nicour** [comment]
JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN  JAN JAN JAN JAN JAN JAN JAN JAN JAN JAN
